TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_INFLATE: False
  CHECKPOINT_EPOCH_RESET: True
  MIXUP_ALPHA: 0.4
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  AUTOAUGMENT: True
  COLORAUGMENT: False
  RANDAUGMENT: False
  RANDOM_FLIP: True
TEMPORAL_HEAD:
  HIDDEN_DIM: 512
  NUM_ATTENTION_HEADS: 8
XVIT:
  BASE_MODEL: lvit_v2_base_patch16_224
  CONSENSUS_TYPE: 'vit'
  USE_XVIT: True
  USE_SpatialShift: True
  SHIFT_SIZE: 1
  SHIFT_DIV: 8
  NUM_SEGMENTS: 8
  LOCATIONS_LIST: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
BN:
  USE_PRECISE_STATS: False
SOLVER:
  BASE_LR: 0.03
  LR_POLICY: cosine
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
  STEPS: [0,20,40]
  LRS: [1.0,0.1,0.01]
MODEL:
  NUM_CLASSES: 400
  ARCH: xvit
  MODEL_NAME: XVIT
  LOSS_FUNC: smooth_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: output/k400_lv2_dts_vvt_St_Ts_cgate
ATTENTION_TYPE: divided_time_space
USE_3D: False
USE_CGATE: True
SAVE_QK: False