TRAIN:
  ENABLE: False
  DATASET: Charades
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_INFLATE: False
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: output/ablation_k400/lvit_baseline_qkvcgate_tempshift_spatialshift/checkpoints/checkpoint_epoch_00040.pyth
  MIXUP_ALPHA: 0.
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 340]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  MULTI_LABEL: True
  STD: [0.5, 0.5, 0.5]
  AUTOAUGMENT: True
  COLORAUGMENT: False
  RANDAUGMENT: False
  RANDOM_FLIP: True
  ENSEMBLE_METHOD: max
TEMPORAL_HEAD:
  HIDDEN_DIM: 512
  NUM_ATTENTION_HEADS: 8
XVIT:
  BASE_MODEL: lvit_v2_base_patch16_224_in21k_finetune1k
  CONSENSUS_TYPE: 'vit'
  USE_XVIT: True
  USE_SpatialShift: True
  SHIFT_SIZE: 1
  SHIFT_DIV: 8
  NUM_SEGMENTS: 8
  LOCATIONS_LIST: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
BN:
  USE_PRECISE_STATS: False
SOLVER:
  BASE_LR: 0.035
  LR_POLICY: cosine
  MAX_EPOCH: 60
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
  STEPS: [0,20,40]
  LRS: [1.0,0.1,0.01]
MODEL:
  NUM_CLASSES: 157
  ARCH: xvit
  MODEL_NAME: XVIT
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: Charades
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 5
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: output/ablation_charades/lvit_baseline_qkvcgate_tempshift_spatialshift_sharegate_finetunek400
ATTENTION_TYPE: divided_time_space
USE_3D: False
USE_CGATE: True
SHARE_GATE: True
SAVE_QK: False